### PR TITLE
log fixes

### LINKED ISSUE #283: Gelf + application error
If gelf enabled application ends with application error, the following is logged:
message: Application error: 147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.wr-google-sheets:1.3.0 container '0-386950909--0-keboola-wr-google-sheets' failed: (2) No error message.

### LINKED ISSUE #291: Log stderr when component timeouts

### PR DESCRIPTION
**Pull request by odinuv**
fix: log stdout when component timeouts, fixes #291
fix: remove stderr log completely on app error, and leave it only in exception data
fix: no error message in application error with gelf only logging, fixes #283

### CODE REVIEW

File: Docker/Container.php [hunk 1]
```diff
@@ -336,20 +332,30 @@ private function handleContainerFailure(Process $process, $startTime)
...
+                    $data
+                );
+            } else {
+                throw new InitializationException(
+                    "{$this->getImage()->getFullImageId()} container terminated. Will restart."
+                );
             }
-            $this->containerLogger->error($buffer);
+        } elseif ($process->getExitCode() == 1) {
+            // syrup will log the process error output as part of the exception body
```
Comment (Halama) [inline Docker/Container.php]: Takže v případě user error to teda zařídí syrup že se to hodí do resultu jobu + zaloguje event s chybou?

Comment (odinuv) [reply Docker/Container.php]: zaloguje https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Command/JobCommand.php#L223 a vrati message v resultu jobu a skonci user chybou https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Command/JobCommand.php#L230

Comment (Halama) [reply Docker/Container.php]: j jasny v tomhle jsem se zrovna vrtal a tady se rozlisi jestli tam message pujde ven pro user error nebo se schova pro internal https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Monolog/Handler/StorageApiHandler.php#L92 takze ok
